[package]
name = "global-illumination"
version = "0.1.0"
edition = "2021"

[dependencies]
gltf = "1.3.0"
image = "0.24.7"
pixels = "0.13.0"
winit = "0.28"
math.git = "https://github.com/mberehulka/nexodia"